version: '3'

services:
  # backend:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - postgresql
  #   volumes:
  #     - ./interview_task:/code
  #   command: sh start_app.sh
  #   networks:
  #     - bitpinNet


  postgresql:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdatabitpin:/var/lib/postgresql/data
    # networks:
    #   - bitpinNet

  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

# networks:
#   bitpinNet:
#     driver: bridge

volumes:
  pgdatabitpin:
